### ISSUE TITLE
Problem Bulding Gradle on Android Studio 3.0.1

### ISSUE THREAD

**Issue by frsfth25** [nraboy/android-minesweeper-game#1]
Firstful, thanks for this, and the tutorial given, it is so helpful and neatly explained.

So, I just tried to open the codes using Android Studio 3.0.1 of mine, however I met several errors during build, so here, I will provide the links that I use for solving according to the particular error.

1. https://stackoverflow.com/questions/42777321/could-not-determine-the-class-path-for-interface-com-android-builder-model-andro
2. https://stackoverflow.com/questions/27233800/android-studio-could-not-find-method-runproguard-for-arguments
3. https://github.com/AntennaPod/AntennaPod/issues/476

**Comment by glider12** [comment]
thank you for the solution

**Comment by glider12** [comment]
thank you for the solution
